# .github/workflows/deploy.yml
name: CI → Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Copy frontend build into software/
        run: |
          mkdir -p software
          cp -R frontend/dist/* software/

      - name: Commit built SPA (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add software
          git commit -m "chore: update built SPA" || echo "no changes to commit"

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: crate-nexus-wms
          heroku_email: markacatherman@gmail.com

