name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # REQUIRED: tell GitHub this is the Pages environment
    environment:
      name: github-pages

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      # Step 1: Configure Pages environment
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Step 2: Upload everything in your repo for Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      # Step 3: Deploy via the latest Pages deploy action
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
