name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Step 1: Configure Pages environment
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Step 2: Upload the entire repo (your HTML/JS) as the Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: |

            .
            !.github/**
            !node_modules/**

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
